name = "borgpad-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "borgpad"
database_id = "xxx"  # L'ID fourni lors de la création 