name = "borgpad-bot"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"] 
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "SESSION_STORE"
id = "f2481cf9dd554236a59ce0416b7578d9"  # Vous obtiendrez cet ID après la création



